{
  "openapi": "3.0.0",
  "info": {
    "title": "Restaurant Listing API",
    "version": "1.0.0",
    "description": "API documentation for Restaurant Listing Application"
  },
  "servers": [
    { "url": "http://localhost:5000", "description": "Development server" }
  ],
  "schemes": ["http"],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "CreateUserInput": {
        "type": "object",
        "required": ["userName", "emailId", "password", "userType"],
        "properties": {
          "userName": {
            "type": "string",
            "minLength": 3,
            "default": "Admin Ram",
            "example": "username"
          },
          "emailId": {
            "type": "string",
            "format": "email",
            "default": "adminram@gmail.com",
            "example": "username@gmail.com"
          },
          "password": {
            "type": "string",
            "minLength": 6,
            "default": "adminpass",
            "example": "userpass"
          },
          "userType": {
            "type": "string",
            "enum": ["admin", "user", "bo"],
            "default": "admin",
            "example": "user"
          }
        }
      },
      "CreateUserResponse": {
        "type": "object",
        "properties": {
          "_id": { "type": "string", "example": "65fe79b1b576257cde2d913e" },
          "userName": { "type": "string", "example": "Admin Ram" },
          "emailId": { "type": "string", "example": "adminram@gmail.com" },
          "userType": { "type": "string", "example": "admin" },
          "accessToken": { "type": "string", "example": "accesstoken" },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-03-23T06:21:36.315Z"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-03-23T06:21:36.315Z"
          }
        }
      },
      "LoginUserInput": {
        "type": "object",
        "required": ["emailId", "password"],
        "properties": {
          "emailId": {
            "type": "string",
            "format": "email",
            "default": "adminram@gmail.com"
          },
          "password": {
            "type": "string",
            "minLength": 6,
            "default": "adminpass"
          }
        }
      },
      "LoginUserResponse": {
        "type": "object",
        "properties": {
          "_id": { "type": "string", "example": "65fe79b1b576257cde2d913e" },
          "userName": { "type": "string", "example": "Admin Ram" },
          "emailId": { "type": "string", "example": "adminram@gmail.com" },
          "userType": { "type": "string", "example": "admin" },
          "accessToken": { "type": "string", "example": "accesstoken" },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-03-23T06:21:36.315Z"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "example": "2024-03-23T06:21:36.315Z"
          }
        }
      },
      "CreateRestaurantListingInput": {
        "type": "object",
        "required": ["restaurantName", "contactInfo", "address"],
        "properties": {
          "restaurantName": {
            "type": "string",
            "minLength": 3,
            "example": "Example Restaurant"
          },
          "contactInfo": {
            "type": "object",
            "properties": {
              "emailId": {
                "type": "string",
                "format": "email",
                "example": "restaurant@gmail.com"
              },
              "phoneNumber": {
                "type": "string",
                "minLength": 10,
                "maxLength": 10,
                "example": 1234567890
              }
            }
          },
          "address": {
            "type": "object",
            "required": ["city", "pincode", "country"],
            "properties": {
              "line_1": { "type": "string", "example": "123 Main Street" },
              "street": { "type": "string", "example": "Downtown" },
              "city": { "type": "string", "example": "City" },
              "pincode": {
                "type": "string",
                "minLength": 6,
                "maxLength": 6,
                "example": 123456
              },
              "country": { "type": "string", "example": "Country" }
            }
          },
          "tableCapacity": { "type": "integer", "example": 50 },
          "images": {
            "type": "array",
            "items": {
              "type": "string",
              "example": "https://example.com/image1.jpg"
            }
          },
          "foodMenu": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "itemName": { "type": "string", "example": "Burger" },
                "itemPrice": { "type": "string", "example": 150 }
              }
            }
          }
        }
      },
      "CreateRestaurantListingResponse": {
        "type": "object",
        "properties": {
          "_id": { "type": "string", "example": "65fe79b1b576257cde2d913e" },
          "restaurantName": {
            "type": "string",
            "example": "Example Restaurant"
          },
          "contactInfo": {
            "type": "object",
            "properties": {
              "emailId": {
                "type": "string",
                "example": "restaurant@gmail.com"
              },
              "phoneNumber": { "type": "string", "example": "1234567890" }
            }
          },
          "address": {
            "type": "object",
            "properties": {
              "line_1": { "type": "string", "example": "123 Main Street" },
              "street": { "type": "string", "example": "Downtown" },
              "city": { "type": "string", "example": "City" },
              "pincode": { "type": "string", "example": "123456" },
              "country": { "type": "string", "example": "Country" }
            }
          },
          "tableCapacity": { "type": "integer", "example": 50 },
          "images": {
            "type": "array",
            "items": {
              "type": "string",
              "example": "https://example.com/image1.jpg"
            }
          },
          "foodMenu": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "itemName": { "type": "string", "example": "Burger" },
                "itemPrice": { "type": "string", "example": "150.00" }
              }
            }
          },
          "createdBy": {
            "type": "object",
            "properties": {
              "_id": { "type": "string", "example": "1234567890" },
              "onwerName": { "type": "string", "example": "Owner Name" },
              "ownerType": { "type": "string", "example": "bo" }
            }
          },
          "reviewsInfo": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": { "type": "string", "example": "1234567890" },
                "review": { "type": "string", "example": "Great restaurant!" },
                "rating": { "type": "number", "example": 5 },
                "reviewerId": { "type": "string", "example": "987654321" },
                "reviewerName": {
                  "type": "string",
                  "example": "Reviewer Name"
                },
                "ownerReply": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": { "type": "string", "example": "1234567890" },
                      "reply": {
                        "type": "string",
                        "example": "Thank you for your review!"
                      },
                      "createdAt": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-03-23T06:21:36.315Z"
                      }
                    }
                  }
                },
                "createdAt": {
                  "type": "string",
                  "format": "date-time",
                  "example": "2024-03-23T06:21:36.315Z"
                }
              }
            }
          }
        }
      },
      "UpdateRestaurantInput": {
        "type": "object",
        "properties": {
          "restaurantName": {
            "type": "string",
            "minLength": 3,
            "example": "Updated Restaurant"
          },
          "contactInfo": {
            "type": "object",
            "properties": {
              "emailId": {
                "type": "string",
                "format": "email",
                "example": "updated.restaurant@gmail.com"
              },
              "phoneNumber": {
                "type": "string",
                "minLength": 10,
                "maxLength": 10,
                "example": "1234567890"
              }
            }
          },
          "address": {
            "type": "object",
            "properties": {
              "line_1": {
                "type": "string",
                "example": "123 Updated Main Street"
              },
              "street": { "type": "string", "example": "Updated Downtown" },
              "city": { "type": "string", "example": "Updated City" },
              "pincode": {
                "type": "string",
                "minLength": 6,
                "maxLength": 6,
                "example": "654321"
              },
              "country": { "type": "string", "example": "Updated Country" }
            }
          },
          "tableCapacity": { "type": "integer", "example": 100 },
          "images": {
            "type": "array",
            "items": {
              "type": "string",
              "example": ["updated_image1.jpg", "updated_image2.jpg"]
            }
          },
          "foodMenu": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "itemName": { "type": "string", "example": "Updated Burger" },
                "itemPrice": { "type": "string", "example": "$7.99" }
              }
            }
          }
        }
      },
      "UpdateRestaurantResponse": {
        "type": "object",
        "properties": {
          "_id": { "type": "string", "example": "65fe79b1b576257cde2d913e" },
          "restaurantName": {
            "type": "string",
            "example": "Updated Restaurant"
          },
          "contactInfo": {
            "type": "object",
            "properties": {
              "emailId": {
                "type": "string",
                "example": "Updated.restaurant@gmail.com"
              },
              "phoneNumber": { "type": "string", "example": "1234567890" }
            }
          },
          "address": {
            "type": "object",
            "properties": {
              "line_1": {
                "type": "string",
                "example": "Updated 123 Main Street"
              },
              "street": { "type": "string", "example": "Updated Downtown" },
              "city": { "type": "string", "example": "Updated City" },
              "pincode": { "type": "string", "example": "Updated 123456" },
              "country": { "type": "string", "example": "Updated Country" }
            }
          },
          "tableCapacity": { "type": "integer", "example": 50 },
          "images": {
            "type": "array",
            "items": {
              "type": "string",
              "example": "https://example.com/Updatedimage1.jpg"
            }
          },
          "foodMenu": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "itemName": { "type": "string", "example": "Updated Burger" },
                "itemPrice": { "type": "string", "example": "150.00" }
              }
            }
          },
          "createdBy": {
            "type": "object",
            "properties": {
              "_id": { "type": "string", "example": "1234567890" },
              "onwerName": { "type": "string", "example": "Owner Name" },
              "ownerType": { "type": "string", "example": "bo" }
            }
          },
          "reviewsInfo": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": { "type": "string", "example": "1234567890" },
                "review": { "type": "string", "example": "Great restaurant!" },
                "rating": { "type": "number", "example": 5 },
                "reviewerId": { "type": "string", "example": "987654321" },
                "reviewerName": {
                  "type": "string",
                  "example": "Reviewer Name"
                },
                "ownerReply": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": { "type": "string", "example": "1234567890" },
                      "reply": {
                        "type": "string",
                        "example": "Thank you for your review!"
                      },
                      "createdAt": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2024-03-23T06:21:36.315Z"
                      }
                    }
                  }
                },
                "createdAt": {
                  "type": "string",
                  "format": "date-time",
                  "example": "2024-03-23T06:21:36.315Z"
                }
              }
            }
          }
        }
      },
      "GetAllRestaurantsResponse": {
        "type": "object",
        "properties": {
          "contactInfo": {
            "type": "object",
            "properties": {
              "emailId": { "type": "string" },
              "phoneNumber": { "type": "string" }
            }
          },
          "address": {
            "type": "object",
            "properties": {
              "line_1": { "type": "string" },
              "street": { "type": "string" },
              "city": { "type": "string" },
              "pincode": { "type": "string" },
              "country": { "type": "string" }
            }
          },
          "createdBy": {
            "type": "object",
            "properties": {
              "_id": { "type": "string" },
              "onwerName": { "type": "string" },
              "ownerType": { "type": "string" }
            }
          },
          "_id": { "type": "string" },
          "restaurantName": { "type": "string" },
          "tableCapacity": { "type": "integer" },
          "images": { "type": "array", "items": { "type": "string" } },
          "foodMenu": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "itemName": { "type": "string" },
                "itemPrice": { "type": "string" },
                "_id": { "type": "string" }
              }
            }
          },
          "reviewsInfo": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": { "type": "string" },
                "review": { "type": "string" },
                "rating": { "type": "integer" },
                "reviewerId": { "type": "string" },
                "reviewerName": { "type": "string" },
                "ownerReply": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "_id": { "type": "string" },
                      "reply": { "type": "string" },
                      "createdAt": { "type": "string" }
                    }
                  }
                },
                "createdAt": { "type": "string" }
              }
            }
          }
        },
        "example": {
          "contactInfo": {
            "emailId": "maduraivillas@gmail.com",
            "phoneNumber": "1234567890"
          },
          "address": {
            "line_1": 12,
            "street": "Vizhakuthoon",
            "city": "Madurai",
            "pincode": "625001",
            "country": "India"
          },
          "createdBy": {
            "_id": "65fc5760a6ebc1c47bdb99ed",
            "onwerName": "BO",
            "ownerType": "bo"
          },
          "_id": "65fd255c18affdf45d849141",
          "restaurantName": "Madurai Villas",
          "tableCapacity": 50,
          "images": ["https://example.com/image1.jpg"],
          "foodMenu": [
            {
              "itemName": "Mutton Biriyani",
              "itemPrice": "210.00",
              "_id": "SjelAZ0CSG"
            },
            {
              "itemName": "Chicken Biriyani",
              "itemPrice": "180.00",
              "_id": "PfCQ9PS09j"
            }
          ],
          "reviewsInfo": [
            {
              "_id": "65fdcee0a5035b763d686521",
              "review": "Food city is Madurai, semma sappadu",
              "rating": 5,
              "reviewerId": "65fd08f34fb8cbd5f05aa159",
              "reviewerName": "Ram Vignesh M",
              "ownerReply": [],
              "createdAt": "2024-03-22T18:33:04.610Z"
            }
          ]
        }
      },
      "DeleteRestaurantResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean", "example": true },
          "data": { "type": "object" },
          "message": { "type": "string", "example": "Deleted successfully!..." }
        }
      },
      "CreateReviewRequest": {
        "type": "object",
        "required": [
          "review",
          "rating",
          "restaurantId",
          "ownerId",
          "reviewType"
        ],
        "properties": {
          "review": { "type": "string" },
          "rating": { "type": "number" },
          "restaurantId": { "type": "string" },
          "ownerId": { "type": "string" },
          "reviewType": { "type": "string" },
          "repliedTo": { "type": "string" }
        },
        "example": {
          "review": "Food city is Madurai, semma sappadu",
          "rating": 5,
          "restaurantId": "65fd255c18affdf45d849141",
          "ownerId": "65fc5760a6ebc1c47bdb99ed",
          "reviewType": "review",
          "repliedTo": ""
        }
      },
      "CreateReviewResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean", "example": true },
          "data": { "type": "object", "example": {} },
          "message": {
            "type": "string",
            "example": "Thank You for the Review!"
          }
        }
      },
      "MyReviewResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean" },
          "data": {
            "type": "object",
            "properties": {
              "myReviews": {
                "type": "array",
                "items": { "$ref": "#/components/schemas/Review" }
              }
            }
          },
          "message": { "type": "string" }
        },
        "example": {
          "status": true,
          "data": {
            "myReviews": [
              {
                "_id": "65fdcee0a5035b763d686521",
                "reviewerId": "65fd08f34fb8cbd5f05aa159",
                "reviewerName": "Ram Vignesh M",
                "review": "Food city is Madurai, semma sappadu",
                "rating": 5,
                "status": "NOTREPLIED",
                "restaurantId": "65fd255c18affdf45d849141",
                "restaurantName": "Madurai Villas",
                "ownerId": "65fc5760a6ebc1c47bdb99ed",
                "reviewType": "review",
                "repliedTo": "",
                "ownerReply": [],
                "createdAt": "2024-03-22T18:33:04.560Z"
              },
              {
                "_id": "65feaceee8bf31b267b531ad",
                "reviewerId": "65fd08f34fb8cbd5f05aa159",
                "reviewerName": "Ram Vignesh M",
                "review": "Food city is Madurai, semma sappadu",
                "rating": 5,
                "status": "REPLIED",
                "restaurantId": "65fd255c18affdf45d849141",
                "restaurantName": "Madurai Villas",
                "ownerId": "65fc5760a6ebc1c47bdb99ed",
                "reviewType": "review",
                "repliedTo": "",
                "ownerReply": [
                  {
                    "_id": "h32GjvMYCQ",
                    "reply": "Thanks for your review Sir!",
                    "createdAt": "2024-03-23T10:22:59.923Z"
                  }
                ],
                "createdAt": "2024-03-23T10:20:30.916Z"
              }
            ]
          },
          "message": "Your reviews retrieved successfully!..."
        }
      },
      "Review": {
        "type": "object",
        "properties": {
          "_id": { "type": "string" },
          "reviewerId": { "type": "string" },
          "reviewerName": { "type": "string" },
          "review": { "type": "string" },
          "rating": { "type": "number" },
          "status": { "type": "string" },
          "restaurantId": { "type": "string" },
          "restaurantName": { "type": "string" },
          "ownerId": { "type": "string" },
          "reviewType": { "type": "string" },
          "repliedTo": { "type": "string" },
          "ownerReply": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": { "type": "string" },
                "reply": { "type": "string" },
                "createdAt": { "type": "string", "format": "date-time" }
              }
            }
          },
          "createdAt": { "type": "string", "format": "date-time" }
        },
        "example": {
          "_id": "65fdcee0a5035b763d686521",
          "reviewerId": "65fd08f34fb8cbd5f05aa159",
          "reviewerName": "Ram Vignesh M",
          "review": "Food city is Madurai, semma sappadu",
          "rating": 5,
          "status": "NOTREPLIED",
          "restaurantId": "65fd255c18affdf45d849141",
          "restaurantName": "Madurai Villas",
          "ownerId": "65fc5760a6ebc1c47bdb99ed",
          "reviewType": "review",
          "repliedTo": "",
          "ownerReply": [],
          "createdAt": "2024-03-22T18:33:04.560Z"
        }
      },
      "BusinessOwnerPendingReviewResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean" },
          "data": {
            "type": "object",
            "properties": {
              "pendingReview": {
                "type": "array",
                "items": { "$ref": "#/components/schemas/Review" }
              }
            }
          },
          "message": { "type": "string" }
        },
        "example": {
          "status": true,
          "data": {
            "pendingReview": [
              {
                "_id": "65fdcee0a5035b763d686521",
                "reviewerId": "65fd08f34fb8cbd5f05aa159",
                "reviewerName": "Ram Vignesh M",
                "review": "Food city is Madurai, semma sappadu",
                "rating": 5,
                "status": "NOTREPLIED",
                "restaurantId": "65fd255c18affdf45d849141",
                "restaurantName": "Madurai Villas",
                "ownerId": "65fc5760a6ebc1c47bdb99ed",
                "reviewType": "review",
                "repliedTo": "",
                "ownerReply": [],
                "createdAt": "2024-03-22T18:33:04.560Z",
                "updatedAt": "2024-03-22T18:33:04.560Z"
              },
              {
                "_id": "65feaceee8bf31b267b531ad",
                "reviewerId": "65fd08f34fb8cbd5f05aa159",
                "reviewerName": "Ram Vignesh M",
                "review": "Food city is Madurai, semma sappadu",
                "rating": 5,
                "status": "NOTREPLIED",
                "restaurantId": "65fd255c18affdf45d849141",
                "restaurantName": "Madurai Villas",
                "ownerId": "65fc5760a6ebc1c47bdb99ed",
                "reviewType": "review",
                "repliedTo": "",
                "ownerReply": [],
                "createdAt": "2024-03-23T10:20:30.916Z",
                "updatedAt": "2024-03-23T10:20:30.916Z"
              }
            ]
          },
          "message": "Success"
        }
      },
      "BusinessOwnerReplyRequestBody": {
        "type": "object",
        "properties": { "reply": { "type": "string" } },
        "example": { "reply": "Thanks for your review Sir!" }
      },
      "BusinessOwnerReplyResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean" },
          "data": {
            "type": "object",
            "properties": {
              "restaurantDetails": {
                "type": "object",
                "properties": {
                  "contactInfo": {
                    "type": "object",
                    "properties": {
                      "emailId": { "type": "string" },
                      "phoneNumber": { "type": "string" }
                    }
                  },
                  "address": {
                    "type": "object",
                    "properties": {
                      "line_1": { "type": "string" },
                      "street": { "type": "string" },
                      "city": { "type": "string" },
                      "pincode": { "type": "string" },
                      "country": { "type": "string" }
                    }
                  },
                  "createdBy": {
                    "type": "object",
                    "properties": {
                      "_id": { "type": "string" },
                      "onwerName": { "type": "string" },
                      "ownerType": { "type": "string" }
                    }
                  },
                  "_id": { "type": "string" },
                  "restaurantName": { "type": "string" },
                  "tableCapacity": { "type": "number" },
                  "images": { "type": "array", "items": { "type": "string" } },
                  "foodMenu": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "_id": { "type": "string" },
                        "itemName": { "type": "string" },
                        "itemPrice": { "type": "string" }
                      }
                    }
                  },
                  "reviewsInfo": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "_id": { "type": "string" },
                        "review": { "type": "string" },
                        "rating": { "type": "number" },
                        "reviewerId": { "type": "string" },
                        "reviewerName": { "type": "string" },
                        "ownerReply": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "_id": { "type": "string" },
                              "reply": { "type": "string" },
                              "createdAt": { "type": "string" }
                            }
                          }
                        },
                        "createdAt": { "type": "string" }
                      }
                    }
                  },
                  "createdAt": { "type": "string" },
                  "updatedAt": { "type": "string" },
                  "__v": { "type": "number" }
                }
              },
              "updatedReviewDetails": {
                "type": "object",
                "properties": {
                  "_id": { "type": "string" },
                  "reviewerId": { "type": "string" },
                  "reviewerName": { "type": "string" },
                  "review": { "type": "string" },
                  "rating": { "type": "number" },
                  "status": { "type": "string" },
                  "restaurantId": { "type": "string" },
                  "restaurantName": { "type": "string" },
                  "ownerId": { "type": "string" },
                  "reviewType": { "type": "string" },
                  "repliedTo": { "type": "string" },
                  "ownerReply": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "_id": { "type": "string" },
                        "reply": { "type": "string" },
                        "createdAt": { "type": "string" }
                      }
                    }
                  },
                  "createdAt": { "type": "string" },
                  "updatedAt": { "type": "string" },
                  "__v": { "type": "number" }
                }
              }
            }
          },
          "message": { "type": "string" }
        },
        "example": {
          "status": true,
          "data": {
            "restaurantDetails": {
              "contactInfo": {
                "emailId": "maduraivillas@gmail.com",
                "phoneNumber": "1234567890"
              },
              "address": {
                "line_1": "12",
                "street": "Vizhakuthoon",
                "city": "Madurai",
                "pincode": "625001",
                "country": "India"
              },
              "createdBy": {
                "_id": "65fc5760a6ebc1c47bdb99ed",
                "onwerName": "BO",
                "ownerType": "bo"
              },
              "_id": "65fd255c18affdf45d849141",
              "restaurantName": "Madurai Villas",
              "tableCapacity": 50,
              "images": ["https://example.com/image1.jpg"],
              "foodMenu": [
                {
                  "_id": "SjelAZ0CSG",
                  "itemName": "Mutton Biriyani",
                  "itemPrice": "210.00"
                },
                {
                  "_id": "PfCQ9PS09j",
                  "itemName": "Chicken Biriyani",
                  "itemPrice": "180.00"
                }
              ],
              "reviewsInfo": [
                {
                  "_id": "65fdcee0a5035b763d686521",
                  "review": "Food city is Madurai, semma sappadu",
                  "rating": 5,
                  "reviewerId": "65fd08f34fb8cbd5f05aa159",
                  "reviewerName": "Ram Vignesh M",
                  "ownerReply": [],
                  "createdAt": "2024-03-22T18:33:04.610Z"
                },
                {
                  "_id": "65feaceee8bf31b267b531ad",
                  "review": "Food city is Madurai, semma sappadu",
                  "rating": 5,
                  "reviewerId": "65fd08f34fb8cbd5f05aa159",
                  "reviewerName": "Ram Vignesh M",
                  "ownerReply": [
                    {
                      "_id": "h32GjvMYCQ",
                      "reply": "Thanks for your review Sir!",
                      "createdAt": "2024-03-23T10:22:59.923Z"
                    }
                  ],
                  "createdAt": "2024-03-23T10:20:30.989Z"
                }
              ],
              "createdAt": "2024-03-22T06:29:48.830Z",
              "updatedAt": "2024-03-23T10:20:30.993Z",
              "__v": 0
            },
            "updatedReviewDetails": {
              "_id": "65feaceee8bf31b267b531ad",
              "reviewerId": "65fd08f34fb8cbd5f05aa159",
              "reviewerName": "Ram Vignesh M",
              "review": "Food city is Madurai, semma sappadu",
              "rating": 5,
              "status": "REPLIED",
              "restaurantId": "65fd255c18affdf45d849141",
              "restaurantName": "Madurai Villas",
              "ownerId": "65fc5760a6ebc1c47bdb99ed",
              "reviewType": "review",
              "repliedTo": "",
              "ownerReply": [
                {
                  "_id": "h32GjvMYCQ",
                  "reply": "Thanks for your review Sir!",
                  "createdAt": "2024-03-23T10:22:59.923Z"
                }
              ],
              "createdAt": "2024-03-23T10:20:30.916Z",
              "updatedAt": "2024-03-23T10:22:59.991Z",
              "__v": 0
            }
          },
          "message": "Replied successfully to User Review"
        }
      },
      "ReviewDeletedResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean" },
          "data": { "type": "object" },
          "message": { "type": "string" }
        },
        "example": {
          "status": true,
          "data": {},
          "message": "Review deleted Successfully!..."
        }
      },
      "UpdateReviewRequest": {
        "type": "object",
        "properties": {
          "review": { "type": "string" },
          "rating": { "type": "number" }
        },
        "required": ["review", "rating"],
        "example": {
          "review": "Food city is Madurai, semma sappadu - update",
          "rating": 5
        }
      },
      "UpdateReviewResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean" },
          "data": { "type": "object" },
          "message": { "type": "string" }
        },
        "example": {
          "status": true,
          "data": {},
          "message": "Your Review updated successfully!..."
        }
      },
      "ReplyUpdateRequest": {
        "type": "object",
        "properties": { "reply": { "type": "string" } },
        "example": { "reply": "Thanks Sir!..." }
      },
      "ReplyUpdateResponse": {
        "type": "object",
        "properties": {
          "status": { "type": "boolean" },
          "data": {
            "type": "object",
            "properties": {
              "contactInfo": {
                "type": "object",
                "properties": {
                  "emailId": { "type": "string" },
                  "phoneNumber": { "type": "string" }
                }
              },
              "address": {
                "type": "object",
                "properties": {
                  "line_1": { "type": "string" },
                  "street": { "type": "string" },
                  "city": { "type": "string" },
                  "pincode": { "type": "string" },
                  "country": { "type": "string" }
                }
              },
              "createdBy": {
                "type": "object",
                "properties": {
                  "_id": { "type": "string" },
                  "onwerName": { "type": "string" },
                  "ownerType": { "type": "string" }
                }
              },
              "_id": { "type": "string" },
              "restaurantName": { "type": "string" },
              "tableCapacity": { "type": "number" },
              "images": { "type": "array", "items": { "type": "string" } },
              "foodMenu": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "_id": { "type": "string" },
                    "itemName": { "type": "string" },
                    "itemPrice": { "type": "string" }
                  }
                }
              },
              "reviewsInfo": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "_id": { "type": "string" },
                    "review": { "type": "string" },
                    "rating": { "type": "number" },
                    "reviewerId": { "type": "string" },
                    "reviewerName": { "type": "string" },
                    "ownerReply": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "_id": { "type": "string" },
                          "reply": { "type": "string" },
                          "createdAt": { "type": "string" }
                        }
                      }
                    },
                    "createdAt": { "type": "string" }
                  }
                }
              },
              "createdAt": { "type": "string" },
              "updatedAt": { "type": "string" },
              "__v": { "type": "number" }
            }
          },
          "message": { "type": "string" }
        },
        "example": {
          "status": true,
          "data": {
            "contactInfo": {
              "emailId": "maduraivillas@gmail.com",
              "phoneNumber": "1234567890"
            },
            "address": {
              "line_1": "12",
              "street": "Vizhakuthoon",
              "city": "Madurai",
              "pincode": "625001",
              "country": "India"
            },
            "createdBy": {
              "_id": "65fc5760a6ebc1c47bdb99ed",
              "onwerName": "BO",
              "ownerType": "bo"
            },
            "_id": "65fd255c18affdf45d849141",
            "restaurantName": "Madurai Villas",
            "tableCapacity": 50,
            "images": ["https://example.com/image1.jpg"],
            "foodMenu": [
              {
                "_id": "SjelAZ0CSG",
                "itemName": "Mutton Biriyani",
                "itemPrice": "210.00"
              },
              {
                "_id": "PfCQ9PS09j",
                "itemName": "Chicken Biriyani",
                "itemPrice": "180.00"
              }
            ],
            "reviewsInfo": [
              {
                "_id": "65fdcee0a5035b763d686521",
                "review": "Food city is Madurai, semma sappadu",
                "rating": 5,
                "reviewerId": "65fd08f34fb8cbd5f05aa159",
                "reviewerName": "Ram Vignesh M",
                "ownerReply": [],
                "createdAt": "2024-03-22T18:33:04.610Z"
              },
              {
                "_id": "65feaceee8bf31b267b531ad",
                "review": "Food city is Madurai, semma sappadu",
                "rating": 5,
                "reviewerId": "65fd08f34fb8cbd5f05aa159",
                "reviewerName": "Ram Vignesh M",
                "ownerReply": [
                  {
                    "_id": "h32GjvMYCQ",
                    "reply": "Thanks Sir!!...",
                    "createdAt": "2024-03-23T10:22:59.923Z"
                  }
                ],
                "createdAt": "2024-03-23T10:20:30.989Z"
              },
              {
                "_id": "65feb331bdf7d67df26d2f1c",
                "review": "Food city is Madurai, semma sappadu",
                "rating": 5,
                "reviewerId": "65fc5783a6ebc1c47bdb99f0",
                "reviewerName": "Admin",
                "ownerReply": [],
                "createdAt": "2024-03-23T10:47:13.540Z"
              }
            ],
            "createdAt": "2024-03-22T06:29:48.830Z",
            "updatedAt": "2024-03-24T05:49:37.502Z",
            "__v": 0
          },
          "message": "Your reviews retrieved successfully!..."
        }
      }
    }
  },
  "security": [{ "bearerAuth": [] }],
  "paths": {
    "/health": {
      "get": {
        "tags": ["Health"],
        "description": "Responds if the app is up and running",
        "responses": { "200": { "description": "To Check if app is up!" } }
      }
    },
    "/api/v1/auth/create-user": {
      "post": {
        "tags": ["User"],
        "summary": "Register a New User",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/CreateUserInput" }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/CreateUserResponse" }
              }
            }
          },
          "400": { "description": "Bad request" },
          "411": { "description": "Length Required" },
          "500": { "description": "Internal Server Error" }
        }
      }
    },
    "/api/v1/auth/signin": {
      "post": {
        "tags": ["User"],
        "summary": "Login User",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/LoginUserInput" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/LoginUserResponse" }
              }
            }
          },
          "400": { "description": "Bad request" },
          "404": { "description": "Not found" },
          "500": { "description": "Internal Server Error" }
        }
      }
    },
    "/api/v1/listing": {
      "get": {
        "tags": ["Restaurant Listing"],
        "summary": "Get all restaurants (All Logged in Users)",
        "description": "Accessed by all types of Roles who are logged in",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": { "type": "boolean" },
                    "data": {
                      "type": "object",
                      "properties": {
                        "restaurantsList": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/GetAllRestaurantsResponse"
                          }
                        },
                        "restaurantCount": { "type": "integer" }
                      }
                    },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          },
          "500": { "description": "Internal Server Error" }
        }
      },
      "delete": {
        "tags": ["Restaurant Listing"],
        "summary": "Delete a restaurant (Admin only)",
        "description": "Delete a restaurant with the restaurantId passed in query param. This route only can accessed by Admin.",
        "parameters": [
          {
            "in": "query",
            "name": "restaurantId",
            "required": true,
            "schema": { "type": "string" },
            "description": "The ID of the restaurant to be deleted"
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Deleted successfully!..."
                    }
                  }
                }
              }
            }
          },
          "400": { "description": "Bad request" },
          "404": { "description": "Not found" },
          "500": { "description": "Internal Server Error" }
        }
      },
      "patch": {
        "tags": ["Restaurant Listing"],
        "summary": "Update a restaurant (Admin or Business Owner only)",
        "description": "Update details of a restaurant. This endpoint is accessible only by users with roles 'admin' or 'bo'. Whereas the Restaurant owned Users from roles bo, admin only can update.",
        "parameters": [
          {
            "in": "query",
            "name": "restaurantId",
            "required": true,
            "schema": { "type": "string" },
            "default": "65fe92a8713299cbaba4ed5f",
            "description": "The ID of the restaurant to be updated"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/UpdateRestaurantInput" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Restaurant updated successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateRestaurantResponse"
                }
              }
            }
          },
          "400": { "description": "Bad request" },
          "401": {
            "description": "Unauthorized - User not allowed to update restaurant"
          },
          "404": { "description": "Restaurant not found" },
          "500": { "description": "Internal Server Error" }
        }
      }
    },
    "/api/v1/listing/create-restaurant": {
      "post": {
        "tags": ["Restaurant Listing"],
        "summary": "Create a new restaurant (Admin or Business Owner only)",
        "description": "This endpoint allows creating a new restaurant. Only users with the role of admin or business owner can access this endpoint.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRestaurantListingInput"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateRestaurantListingResponse"
                }
              }
            }
          },
          "400": { "description": "Bad request" },
          "401": { "description": "Unauthorized" },
          "403": { "description": "Forbidden" },
          "404": { "description": "Not found" },
          "500": { "description": "Internal Server Error" }
        }
      }
    },
    "/api/v1/review/create-review": {
      "post": {
        "tags": ["Review"],
        "summary": "Create a review (Access - Admin, User)",
        "description": "Admin & User can create a review on a restaurant",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/CreateReviewRequest" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Review created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateReviewResponse"
                }
              }
            }
          },
          "400": { "description": "Bad request" },
          "404": { "description": "Not found" },
          "500": { "description": "Internal Server Error" }
        }
      }
    },
    "/api/v1/review": {
      "delete": {
        "tags": ["Review"],
        "summary": "Delete a review (Access - Admin, User)",
        "description": "Delete a review by its reviewId and restaurantId. Admin can delete any review, but User can only delete their own review.",
        "parameters": [
          {
            "in": "query",
            "name": "reviewId",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "restaurantId",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ReviewDeletedResponse"
                }
              }
            }
          },
          "400": { "description": "Bad Request" },
          "401": { "description": "Unauthorized to Delete" },
          "404": {
            "description": "No Review Found to Delete or Given Restaurant Details not correct"
          },
          "500": { "description": "Internal Server Error" }
        }
      },
      "patch": {
        "tags": ["Review"],
        "summary": "Update Reply (Access - Admin & User)",
        "description": "Admin & User can update to their Review if they created it.",
        "parameters": [
          {
            "in": "query",
            "name": "reviewId",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "restaurantId",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/UpdateReviewRequest" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response with updated review details.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateReviewResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request, missing or invalid parameters."
          },
          "401": {
            "description": "Unauthorized access, user not authorized to update review."
          },
          "404": { "description": "Review or restaurant not found." },
          "500": { "description": "Internal server error." }
        }
      }
    },
    "/api/v1/review/reply": {
      "post": {
        "tags": ["Review"],
        "summary": "Reply to a review (Access - Buisness Owner & Admin)",
        "description": "Buisness Owner & Admin can Reply to a review only if they are owner of Restaurant",
        "parameters": [
          {
            "in": "query",
            "name": "reviewId",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "restaurantId",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BusinessOwnerReplyRequestBody"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BusinessOwnerReplyResponse"
                }
              }
            }
          },
          "400": { "description": "Bad Request" },
          "404": { "description": "Not Found" },
          "500": { "description": "Internal Server Error" }
        }
      }
    },
    "/api/v1/review/reply-update": {
      "patch": {
        "tags": ["Review"],
        "summary": "Update Reply (Access - Buisness Owner & Admin)",
        "description": "Buisness Owner & Admin can update to their Reply to a review only if they are owner of Restaurant",
        "parameters": [
          {
            "in": "query",
            "name": "replyId",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "reviewId",
            "required": true,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "restaurantId",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/ReplyUpdateRequest" }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ReplyUpdateResponse" }
              }
            }
          },
          "400": { "description": "Bad request" },
          "401": { "description": "Unauthorized" },
          "404": { "description": "Not found" },
          "500": { "description": "Internal server error" }
        }
      }
    },
    "/api/v1/review/getMyReviews": {
      "get": {
        "tags": ["Review"],
        "summary": "Get reviews submitted (Access - Logged in User)",
        "description": "Get reviews submitted by UserId from JWT Token",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/MyReviewResponse" }
              }
            }
          },
          "500": { "description": "Internal Server Error" }
        }
      }
    },
    "/api/v1/review/bo/getPendingReviews": {
      "get": {
        "tags": ["Review"],
        "summary": "Get pending reviews (Access - Business Owner)",
        "description": "Get pending reviews for a business owner to reply. Accessed only by Logged in Business Owner.",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BusinessOwnerPendingReviewResponse"
                }
              }
            }
          },
          "500": { "description": "Internal Server Error" }
        }
      }
    }
  },
  "tags": []
}
